/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all element codenames
 */
export const elementCodenames = [
	"header",
	"body_copy",
	"image",
	"button_text",
	"button_link",
	"name",
	"images",
	"product_type",
	"body_benefits",
	"more_information",
	"about_the_product",
	"how_to_use",
	"our_formula",
	"quality_assurance",
	"recommended_products",
	"product_catalog",
	"api_previewer",
	"title",
	"hero_image",
	"category",
	"featured_products",
	"call_to_action"
] as const

/*
 * Type representing all element codenames
 */
export type ElementCodenames = (typeof elementCodenames)[number]

/*
 * Typeguard for element codename
 */
export function isElementCodename(value: string | undefined | null): value is ElementCodenames {
	return typeof value === "string" && (elementCodenames as readonly string[]).includes(value)
}
