/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { IDeliveryClient } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "./collections.generated"
import type { ElementCodenames } from "./elements.generated"
import type { LanguageCodenames } from "./languages.generated"
import type { TaxonomyCodenames } from "./taxonomies.generated"
import type { CoreType, TypeCodenames } from "./types.generated"
import type { WorkflowCodenames, WorkflowStepCodenames } from "./workflows.generated"

/*
 * Core types for 'IDeliveryClient'
 */
export type CoreClientTypes = {
	readonly collectionCodenames: CollectionCodenames
	readonly contentItemType: CoreType
	readonly contentTypeCodenames: TypeCodenames
	readonly elementCodenames: ElementCodenames
	readonly languageCodenames: LanguageCodenames
	readonly taxonomyCodenames: TaxonomyCodenames
	readonly workflowCodenames: WorkflowCodenames
	readonly workflowStepCodenames: WorkflowStepCodenames
}

/*
 * Typed delivery client. Use this instead of 'IDeliveryClient'
 */
export type CoreDeliveryClient = IDeliveryClient<CoreClientTypes>
