/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all snippet codenames
 */
export const snippetCodenames = [] as const

/*
 * Type representing all snippet codenames
 */
export type SnippetCodenames = (typeof snippetCodenames)[number]

/*
 * Typeguard for snippet codename
 */
export function isSnippetCodename(value: string | undefined | null): value is SnippetCodenames {
	return typeof value === "string" && (snippetCodenames as readonly string[]).includes(value)
}
