/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all taxonomy codenames
 */
export const taxonomyCodenames = ["body_benefits", "product_type"] as const

/*
 * Type representing all taxonomy codenames
 */
export type TaxonomyCodenames = (typeof taxonomyCodenames)[number]

/*
 * Typeguard for taxonomy codename
 */
export function isTaxonomyCodename(value: string | undefined | null): value is TaxonomyCodenames {
	return typeof value === "string" && (taxonomyCodenames as readonly string[]).includes(value)
}
