/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Array of all workflow codenames
 */
export const workflowCodenames = ["default"] as const

/*
 * Type representing all workflow codenames
 */
export type WorkflowCodenames = (typeof workflowCodenames)[number]

/*
 * Typeguard for workflow codename
 */
export function isWorkflowCodename(value: string | undefined | null): value is WorkflowCodenames {
	return typeof value === "string" && (workflowCodenames as readonly string[]).includes(value)
}

/*
 * Array of all workflow codenames
 */
export const workflowStepCodenames = ["draft", "published", "archived", "scheduled"] as const

/*
 * Type representing all workflow codenames
 */
export type WorkflowStepCodenames = (typeof workflowStepCodenames)[number]

/*
 * Typeguard for workflow codename
 */
export function isWorkflowStepCodename(value: string | undefined | null): value is WorkflowStepCodenames {
	return typeof value === "string" && (workflowStepCodenames as readonly string[]).includes(value)
}
