/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

export const assetFolders = {
	/*
	 * Thumbnails
	 */
	thumbnails: {
		name: "Thumbnails",
		codename: "thumbnails",
		id: "760fa8df-a7ea-489d-8637-616c1d232d11",
		externalId: undefined,
		folders: {}
	},

	/*
	 * CTAs
	 */
	ctas: {
		name: "CTAs",
		codename: "ctas",
		id: "2accbefb-41ca-4aac-9f4f-cea49f628426",
		externalId: undefined,
		folders: {}
	},

	/*
	 * Products
	 */
	products: {
		name: "Products",
		codename: "products",
		id: "a8c4029b-d90b-4376-9735-979a1d5874c2",
		externalId: undefined,
		folders: {}
	}
} as const
