/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

export const collections = {
	/*
	 * Default
	 */
	default: {
		name: "Default",
		codename: "default",
		id: "00000000-0000-0000-0000-000000000000"
	}
} as const
