/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

export const contentTypes = {
	/*
	 * Disclaimer
	 */
	disclaimer: {
		name: "Disclaimer",
		codename: "disclaimer",
		id: "1625b6d0-c653-498c-8bf2-acf59d97bbbf",
		externalId: undefined,
		elements: {
			/*
			 * Header
			 */
			header: {
				name: "Header",
				codename: "header",
				id: "8fd6c855-3ae7-4138-89e4-4f832252325c",
				externalId: undefined,
				required: false,
				type: "text"
			},

			/*
			 * Body Copy
			 */
			body_copy: {
				name: "Body Copy",
				codename: "body_copy",
				id: "0668f753-1412-416b-9638-8e0c2b36ce3a",
				externalId: undefined,
				required: false,
				type: "rich_text"
			}
		}
	},

	/*
	 * Call to Action
	 */
	call_to_action: {
		name: "Call to Action",
		codename: "call_to_action",
		id: "e555773e-08e5-4010-b000-40337dbc9063",
		externalId: undefined,
		elements: {
			/*
			 * Header
			 */
			header: {
				name: "Header",
				codename: "header",
				id: "35c9dae9-c721-4628-be65-7a57fc9f63b4",
				externalId: undefined,
				required: true,
				type: "text"
			},

			/*
			 * Image
			 */
			image: {
				name: "Image",
				codename: "image",
				id: "ffbadb5c-7f7c-4a6e-bfc4-297a9d9b3698",
				externalId: undefined,
				required: true,
				type: "asset"
			},

			/*
			 * Body Copy
			 */
			body_copy: {
				name: "Body Copy",
				codename: "body_copy",
				id: "a6b7cd43-4128-4c6c-977d-61dfc2504f80",
				externalId: undefined,
				required: false,
				type: "rich_text"
			},

			/*
			 * Button Text
			 */
			button_text: {
				name: "Button Text",
				codename: "button_text",
				id: "627ce3c6-5894-43c5-aef6-98d1bf60fc06",
				externalId: undefined,
				required: false,
				type: "text"
			},

			/*
			 * Button Link
			 */
			button_link: {
				name: "Button Link",
				codename: "button_link",
				id: "1fc26292-fea0-47eb-9b07-f19a9a108738",
				externalId: undefined,
				required: false,
				type: "text"
			}
		}
	},

	/*
	 * Product
	 */
	product: {
		name: "Product",
		codename: "product",
		id: "ea895149-eb50-409a-b3df-a57e59dbbc9b",
		externalId: undefined,
		elements: {
			/*
			 * Name
			 */
			name: {
				name: "Name",
				codename: "name",
				id: "a13af2be-fa32-4d7e-aef2-d39e533aabe2",
				externalId: undefined,
				required: true,
				type: "text"
			},

			/*
			 * Images
			 */
			images: {
				name: "Images",
				codename: "images",
				id: "0aa8d455-ef70-46a6-b02b-c870903b3c66",
				externalId: undefined,
				required: true,
				type: "asset"
			},

			/*
			 * Product Type
			 */
			product_type: {
				name: "Product Type",
				codename: "product_type",
				id: "17ba34bb-fba7-4d09-b9da-c3867e96ee9f",
				externalId: undefined,
				required: true,
				type: "taxonomy"
			},

			/*
			 * Body Benefits
			 */
			body_benefits: {
				name: "Body Benefits",
				codename: "body_benefits",
				id: "316c4d72-ef4e-4c45-b681-1c1ff958f42a",
				externalId: undefined,
				required: true,
				type: "taxonomy"
			},

			/*
			 * More Information
			 */
			more_information: {
				name: "More Information",
				codename: "more_information",
				id: "a4264c82-f21e-4eab-97e7-da354002ac1c",
				externalId: undefined,
				required: false,
				type: "rich_text"
			},

			/*
			 * About the Product
			 */
			about_the_product: {
				name: "About the Product",
				codename: "about_the_product",
				id: "9d6f8549-bc97-4aaf-9bdc-6861acbab967",
				externalId: undefined,
				required: false,
				type: "rich_text"
			},

			/*
			 * How to use
			 */
			how_to_use: {
				name: "How to use",
				codename: "how_to_use",
				id: "75e5a725-76d9-4f5d-87a9-34bb78e6ed25",
				externalId: undefined,
				required: false,
				type: "rich_text"
			},

			/*
			 * Our formula
			 */
			our_formula: {
				name: "Our formula",
				codename: "our_formula",
				id: "b5c7829a-8696-480b-935b-f113df5dc8ac",
				externalId: undefined,
				required: false,
				type: "rich_text"
			},

			/*
			 * Quality Assurance
			 */
			quality_assurance: {
				name: "Quality Assurance",
				codename: "quality_assurance",
				id: "69e17eb6-20f3-40ac-8a4a-551c0979e848",
				externalId: undefined,
				required: false,
				type: "modular_content"
			},

			/*
			 * Recommended Products
			 */
			recommended_products: {
				name: "Recommended Products",
				codename: "recommended_products",
				id: "74e9df3e-0e1f-4bd5-ae05-fac678b51e16",
				externalId: undefined,
				required: false,
				type: "modular_content"
			},

			/*
			 * Product Catalog
			 *
			 * Guidelines: CommerceTools integration via custom element
			 */
			product_catalog: {
				name: "Product Catalog",
				codename: "product_catalog",
				id: "b1f8b5a3-71c3-4833-8bb9-34e478e2667b",
				externalId: undefined,
				required: true,
				type: "custom"
			},

			/*
			 * API Previewer
			 */
			api_previewer: {
				name: "API Previewer",
				codename: "api_previewer",
				id: "a6191779-ce6a-479b-a5ad-2facb0355f5a",
				externalId: undefined,
				required: false,
				type: "custom"
			}
		}
	},

	/*
	 * Page
	 */
	page: {
		name: "Page",
		codename: "page",
		id: "bc28363e-f5a1-4cb3-805b-82f31ff3a784",
		externalId: undefined,
		elements: {
			/*
			 * Title
			 */
			title: {
				name: "Title",
				codename: "title",
				id: "c56f9d0e-2eca-40ee-89c5-a0844fa8daa6",
				externalId: undefined,
				required: true,
				type: "text"
			},

			/*
			 * Body Copy
			 */
			body_copy: {
				name: "Body Copy",
				codename: "body_copy",
				id: "3b980867-1078-4bc4-b462-ef9458514633",
				externalId: undefined,
				required: false,
				type: "rich_text"
			},

			/*
			 * Hero image
			 */
			hero_image: {
				name: "Hero image",
				codename: "hero_image",
				id: "87934b51-9a7d-4c8e-b3a9-f0ffb8397096",
				externalId: undefined,
				required: true,
				type: "asset"
			},

			/*
			 * Product Type
			 */
			category: {
				name: "Product Type",
				codename: "category",
				id: "8860d00d-042a-4843-ae78-e6555023c379",
				externalId: undefined,
				required: false,
				type: "taxonomy"
			}
		}
	},

	/*
	 * Landing Page
	 */
	landing_page: {
		name: "Landing Page",
		codename: "landing_page",
		id: "016a17a6-c9bb-4c03-866f-1205a00a769b",
		externalId: undefined,
		elements: {
			/*
			 * Title
			 */
			title: {
				name: "Title",
				codename: "title",
				id: "07957699-6d50-4772-98f6-6d23c1f47c20",
				externalId: undefined,
				required: true,
				type: "text"
			},

			/*
			 * Hero image
			 */
			hero_image: {
				name: "Hero image",
				codename: "hero_image",
				id: "82db1546-2ce1-40a5-8d47-05ba28522226",
				externalId: undefined,
				required: true,
				type: "asset"
			},

			/*
			 * Body Copy
			 */
			body_copy: {
				name: "Body Copy",
				codename: "body_copy",
				id: "61691ef9-cef2-4807-8d29-fa2c001d34f5",
				externalId: undefined,
				required: false,
				type: "rich_text"
			},

			/*
			 * Featured Products
			 */
			featured_products: {
				name: "Featured Products",
				codename: "featured_products",
				id: "b05063d4-beec-47c9-b3a6-6cfc9d65a012",
				externalId: undefined,
				required: false,
				type: "modular_content"
			},

			/*
			 * Call to Action
			 */
			call_to_action: {
				name: "Call to Action",
				codename: "call_to_action",
				id: "c27e246e-b2b5-4557-a690-1e84fb17fa50",
				externalId: undefined,
				required: false,
				type: "modular_content"
			}
		}
	}
} as const
