/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

export const customApps = {
	/*
	 * Model visualizer
	 */
	modelVisualizer: {
		name: "Model visualizer",
		codename: "model_visualizer",
		sourceUrl: "https://subtle-puffpuff-629597.netlify.app/"
	}
} as const
