/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

export const previewUrls = {
	spaceDomains: {
		demo: {
			spaceName: "Website",
			spaceCodename: "demo",
			domain: "enngage.github.io/kontent-ai-usana-demo"
		}
	},
	previewUrlPatterns: {
		landing_page: {
			contentTypeName: "Landing Page",
			contentTypeCodename: "landing_page",
			urlPatterns: {
				default: {
					spaceName: undefined,
					spaceCodename: undefined,
					url: "https://{Space}/"
				}
			}
		},

		product: {
			contentTypeName: "Product",
			contentTypeCodename: "product",
			urlPatterns: {
				default: {
					spaceName: undefined,
					spaceCodename: undefined,
					url: "https://{Space}/product/{Codename}"
				}
			}
		}
	}
} as const
