/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

export const spaces = {
	/*
	 * Website
	 */
	demo: {
		name: "Website",
		codename: "demo",
		id: "1a68fb22-f957-4d5b-9919-c00a358fd1b8"
	}
} as const
