/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

export const taxonomies = {
	/*
	 * Body Benefits
	 */
	body_benefits: {
		name: "Body Benefits",
		codename: "body_benefits",
		externalId: undefined,
		id: "4b9fe04f-ead0-47e7-af82-90da100b963d",
		terms: {
			/*
			 * Heart Health
			 */
			heart_health: {
				name: "Heart Health",
				codename: "heart_health",
				id: "5dd5ca9a-bfad-4e29-a2c4-d48027aeaf22",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Joint Health
			 */
			joint_health: {
				name: "Joint Health",
				codename: "joint_health",
				id: "78defefd-1867-4858-ac4d-4d6de1865dff",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Brain Health
			 */
			brain_health: {
				name: "Brain Health",
				codename: "brain_health",
				id: "c3c3cdeb-a3a7-4eda-86b4-6fcc0a3e4d73",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Immune Health
			 */
			immune_health: {
				name: "Immune Health",
				codename: "immune_health",
				id: "83421427-34b0-4286-815c-0c15cc7c1856",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Digestive Health
			 */
			digestive_health: {
				name: "Digestive Health",
				codename: "digestive_health",
				id: "85e6f966-bc34-45ca-bab7-b62cadf0056a",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Healthy Energy
			 */
			healthy_energy: {
				name: "Healthy Energy",
				codename: "healthy_energy",
				id: "58a3ee94-f75e-42b7-94ec-f1a2473cd9ad",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Skin Health
			 */
			skin_health: {
				name: "Skin Health",
				codename: "skin_health",
				id: "0dad4568-d31f-46f8-aa71-cf9596c81990",
				externalId: undefined,
				terms: {}
			}
		}
	},

	/*
	 * Product Type
	 */
	product_type: {
		name: "Product Type",
		codename: "product_type",
		externalId: undefined,
		id: "8d3852a1-d327-43ac-944e-64f58ae3ea7c",
		terms: {
			/*
			 * Nutritionals
			 */
			nutritionals: {
				name: "Nutritionals",
				codename: "nutritionals",
				id: "c5227c24-2bd8-4dbf-99be-07df4bd72f5b",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Essentials
			 */
			essentials: {
				name: "Essentials",
				codename: "essentials",
				id: "cc2f7d37-f32a-41fa-baeb-b239bfb8f696",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Optimizers
			 */
			optimizers: {
				name: "Optimizers",
				codename: "optimizers",
				id: "04df467f-174c-465f-a665-a019e2e473ea",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Mood & Relaxation
			 */
			mood_relaxation: {
				name: "Mood & Relaxation",
				codename: "mood_relaxation",
				id: "a6f5373f-d020-4347-a545-b40907ca3ae4",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Digestion/Detox
			 */
			digestion_detox: {
				name: "Digestion/Detox",
				codename: "digestion_detox",
				id: "1723d32f-d43a-4290-9f0d-1603f35a503b",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Mother/Child
			 */
			mother_child: {
				name: "Mother/Child",
				codename: "mother_child",
				id: "2fded844-e330-4417-8fce-31b62ef407aa",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Skincare
			 */
			skincare: {
				name: "Skincare",
				codename: "skincare",
				id: "18712d95-43ce-4f1f-be99-015ce35808d1",
				externalId: undefined,
				terms: {}
			},

			/*
			 * Protein, Shakes, & Bars
			 */
			protein__shakes____bars: {
				name: "Protein, Shakes, & Bars",
				codename: "protein__shakes____bars",
				id: "5b1f7d8e-747a-4ba8-80d3-44accc2625da",
				externalId: undefined,
				terms: {}
			}
		}
	}
} as const
