/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated"
import type { LanguageCodenames } from "../system/languages.generated"
import type { CoreType, TypeCodenames } from "../system/types.generated"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated"

/*
 * Type representing codename of 'Call to Action' type
 */
export type CallToActionCodename = keyof Pick<Record<TypeCodenames, null>, "call_to_action">

/*
 * Typeguard for codename of 'Call to Action' type
 */
export function isCallToActionCodename(value: string | undefined | null): value is CallToActionCodename {
	return typeof value === "string" && value === ("call_to_action" satisfies CallToActionCodename)
}

/*
 * Call to Action
 *
 * Id: e555773e-08e5-4010-b000-40337dbc9063
 * Codename: call_to_action
 */
export type CallToAction = IContentItem<
	{
		/*
		 * Header
		 *
		 * Codename: header
		 * Id: 35c9dae9-c721-4628-be65-7a57fc9f63b4
		 * Type: text
		 * Required: true
		 */
		readonly header: Elements.TextElement

		/*
		 * Image
		 *
		 * Codename: image
		 * Id: ffbadb5c-7f7c-4a6e-bfc4-297a9d9b3698
		 * Type: asset
		 * Required: true
		 */
		readonly image: Elements.AssetsElement

		/*
		 * Body Copy
		 *
		 * Codename: body_copy
		 * Id: a6b7cd43-4128-4c6c-977d-61dfc2504f80
		 * Type: rich_text
		 * Required: false
		 */
		readonly body_copy: Elements.RichTextElement<CoreType>

		/*
		 * Button Text
		 *
		 * Codename: button_text
		 * Id: 627ce3c6-5894-43c5-aef6-98d1bf60fc06
		 * Type: text
		 * Required: false
		 */
		readonly button_text: Elements.TextElement

		/*
		 * Button Link
		 *
		 * Codename: button_link
		 * Id: 1fc26292-fea0-47eb-9b07-f19a9a108738
		 * Type: text
		 * Required: false
		 */
		readonly button_link: Elements.TextElement
	},
	CallToActionCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Call to Action
 */
export type CallToActionElementCodenames = "header" | "image" | "body_copy" | "button_text" | "button_link"

/*
 * Type guard for Call to Action
 *
 * Id: e555773e-08e5-4010-b000-40337dbc9063
 * Codename: call_to_action
 */
export function isCallToAction(item: IContentItem | undefined | null): item is CallToAction {
	return item?.system.type === ("call_to_action" satisfies CallToActionCodename)
}
