/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { Elements, IContentItem } from "@kontent-ai/delivery-sdk"
import type { CollectionCodenames } from "../system/collections.generated"
import type { LanguageCodenames } from "../system/languages.generated"
import type { CoreType, TypeCodenames } from "../system/types.generated"
import type { WorkflowCodenames, WorkflowStepCodenames } from "../system/workflows.generated"
import type { CallToAction } from "../types/call-to-action-type.generated"
import type { Product } from "../types/product-type.generated"

/*
 * Type representing codename of 'Landing Page' type
 */
export type LandingPageCodename = keyof Pick<Record<TypeCodenames, null>, "landing_page">

/*
 * Typeguard for codename of 'Landing Page' type
 */
export function isLandingPageCodename(value: string | undefined | null): value is LandingPageCodename {
	return typeof value === "string" && value === ("landing_page" satisfies LandingPageCodename)
}

/*
 * Landing Page
 *
 * Id: 016a17a6-c9bb-4c03-866f-1205a00a769b
 * Codename: landing_page
 */
export type LandingPage = IContentItem<
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: 07957699-6d50-4772-98f6-6d23c1f47c20
		 * Type: text
		 * Required: true
		 */
		readonly title: Elements.TextElement

		/*
		 * Hero image
		 *
		 * Codename: hero_image
		 * Id: 82db1546-2ce1-40a5-8d47-05ba28522226
		 * Type: asset
		 * Required: true
		 */
		readonly hero_image: Elements.AssetsElement

		/*
		 * Body Copy
		 *
		 * Codename: body_copy
		 * Id: 61691ef9-cef2-4807-8d29-fa2c001d34f5
		 * Type: rich_text
		 * Required: false
		 */
		readonly body_copy: Elements.RichTextElement<CoreType>

		/*
		 * Featured Products
		 *
		 * Codename: featured_products
		 * Id: b05063d4-beec-47c9-b3a6-6cfc9d65a012
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: product
		 */
		readonly featured_products: Elements.LinkedItemsElement<Product>

		/*
		 * Call to Action
		 *
		 * Codename: call_to_action
		 * Id: c27e246e-b2b5-4557-a690-1e84fb17fa50
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: call_to_action
		 */
		readonly call_to_action: Elements.LinkedItemsElement<CallToAction>
	},
	LandingPageCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
>

/*
 * Type representing all available element codenames for Landing Page
 */
export type LandingPageElementCodenames = "title" | "hero_image" | "body_copy" | "featured_products" | "call_to_action"

/*
 * Type guard for Landing Page
 *
 * Id: 016a17a6-c9bb-4c03-866f-1205a00a769b
 * Codename: landing_page
 */
export function isLandingPage(item: IContentItem | undefined | null): item is LandingPage {
	return item?.system.type === ("landing_page" satisfies LandingPageCodename)
}
