/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated"

/*
 * Type representing codename of 'Body Benefits' taxonomy
 */
export type BodyBenefitsTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "body_benefits">

/*
 * Typeguard for codename of 'Body Benefits' taxonomy
 */
export function isBodyBenefitsTaxonomyCodename(value: string | undefined | null): value is BodyBenefitsTaxonomyCodename {
	return typeof value === "string" && value === ("body_benefits" satisfies BodyBenefitsTaxonomyCodename)
}

/*
 * Array of all taxonomy term codenames
 */
export const bodyBenefitsTaxonomyTermCodenames = [
	"heart_health",
	"joint_health",
	"brain_health",
	"immune_health",
	"digestive_health",
	"healthy_energy",
	"skin_health"
] as const

/*
 * Type representing all taxonomy term codenames
 */
export type BodyBenefitsTaxonomyTermCodenames = (typeof bodyBenefitsTaxonomyTermCodenames)[number]

/*
 * Typeguard for taxonomy term codename
 */
export function isBodyBenefitsTaxonomyTermCodename(value: string | undefined | null): value is BodyBenefitsTaxonomyTermCodenames {
	return typeof value === "string" && (bodyBenefitsTaxonomyTermCodenames as readonly string[]).includes(value)
}
