/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { TaxonomyCodenames } from "../system/taxonomies.generated"

/*
 * Type representing codename of 'Product Type' taxonomy
 */
export type ProductTypeTaxonomyCodename = keyof Pick<Record<TaxonomyCodenames, null>, "product_type">

/*
 * Typeguard for codename of 'Product Type' taxonomy
 */
export function isProductTypeTaxonomyCodename(value: string | undefined | null): value is ProductTypeTaxonomyCodename {
	return typeof value === "string" && value === ("product_type" satisfies ProductTypeTaxonomyCodename)
}

/*
 * Array of all taxonomy term codenames
 */
export const productTypeTaxonomyTermCodenames = [
	"nutritionals",
	"essentials",
	"optimizers",
	"mood_relaxation",
	"digestion_detox",
	"mother_child",
	"skincare",
	"protein__shakes____bars"
] as const

/*
 * Type representing all taxonomy term codenames
 */
export type ProductTypeTaxonomyTermCodenames = (typeof productTypeTaxonomyTermCodenames)[number]

/*
 * Typeguard for taxonomy term codename
 */
export function isProductTypeTaxonomyTermCodename(value: string | undefined | null): value is ProductTypeTaxonomyTermCodenames {
	return typeof value === "string" && (productTypeTaxonomyTermCodenames as readonly string[]).includes(value)
}
