/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { WorkflowCodenames } from "../system/workflows.generated"

/*
 * Type representing codename of 'Default' workflow
 */
export type DefaultWorkflowCodename = keyof Pick<Record<WorkflowCodenames, null>, "default">

/*
 * Typeguard for codename of 'Default' workflow
 */
export function isDefaultWorkflowCodename(value: string | undefined | null): value is DefaultWorkflowCodename {
	return typeof value === "string" && value === ("default" satisfies DefaultWorkflowCodename)
}

/*
 * Array of all workflow step codenames
 */
export const defaultWorkflowStepCodenames = ["draft", "published", "archived", "scheduled"] as const

/*
 * Type representing all workflow step codenames
 */
export type DefaultWorkflowStepCodenames = (typeof defaultWorkflowStepCodenames)[number]

/*
 * Typeguard for workflow step codename
 */
export function isDefaultWorkflowStepCodename(value: string | undefined | null): value is DefaultWorkflowStepCodenames {
	return typeof value === "string" && (defaultWorkflowStepCodenames as readonly string[]).includes(value)
}
