/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { SyncClient, SyncClientTypes } from "@kontent-ai/sync-sdk"

/*
 * Use as generic type when creating a sync client for increased type safety
 */
export type CoreSyncClientTypes = SyncClientTypes & {
	readonly languageCodenames: "default"
	readonly typeCodenames: "call_to_action" | "disclaimer" | "landing_page" | "page" | "product"
	readonly workflowCodenames: "default"
	readonly workflowStepCodenames: "draft"
	readonly collectionCodenames: "default"
	readonly taxonomyCodenames: "body_benefits" | "product_type"
}

/*
 * Type safe sync client
 */
export type CoreSyncClient = SyncClient<CoreSyncClientTypes>
