/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { MigrationElementModels } from "@kontent-ai/migration-toolkit"
import type { CoreMigrationItem } from "../migration.generated"

/*
 * Call to Action
 *
 * Codename: call_to_action
 * Id: e555773e-08e5-4010-b000-40337dbc9063
 */
export type CallToActionItem = CoreMigrationItem<
	"call_to_action",
	{
		/*
		 * Header
		 *
		 * Codename: header
		 * Id: 35c9dae9-c721-4628-be65-7a57fc9f63b4
		 * Type: text
		 * Required: true
		 */
		readonly header: MigrationElementModels.TextElement

		/*
		 * Image
		 *
		 * Codename: image
		 * Id: ffbadb5c-7f7c-4a6e-bfc4-297a9d9b3698
		 * Type: asset
		 * Required: true
		 */
		readonly image: MigrationElementModels.AssetElement

		/*
		 * Body Copy
		 *
		 * Codename: body_copy
		 * Id: a6b7cd43-4128-4c6c-977d-61dfc2504f80
		 * Type: rich_text
		 * Required: false
		 */
		readonly body_copy: MigrationElementModels.RichTextElement

		/*
		 * Button Text
		 *
		 * Codename: button_text
		 * Id: 627ce3c6-5894-43c5-aef6-98d1bf60fc06
		 * Type: text
		 * Required: false
		 */
		readonly button_text: MigrationElementModels.TextElement

		/*
		 * Button Link
		 *
		 * Codename: button_link
		 * Id: 1fc26292-fea0-47eb-9b07-f19a9a108738
		 * Type: text
		 * Required: false
		 */
		readonly button_link: MigrationElementModels.TextElement
	}
>
