/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { MigrationElementModels } from "@kontent-ai/migration-toolkit"
import type { CoreMigrationItem } from "../migration.generated"

/*
 * Disclaimer
 *
 * Codename: disclaimer
 * Id: 1625b6d0-c653-498c-8bf2-acf59d97bbbf
 */
export type DisclaimerItem = CoreMigrationItem<
	"disclaimer",
	{
		/*
		 * Header
		 *
		 * Codename: header
		 * Id: 8fd6c855-3ae7-4138-89e4-4f832252325c
		 * Type: text
		 * Required: false
		 */
		readonly header: MigrationElementModels.TextElement

		/*
		 * Body Copy
		 *
		 * Codename: body_copy
		 * Id: 0668f753-1412-416b-9638-8e0c2b36ce3a
		 * Type: rich_text
		 * Required: false
		 */
		readonly body_copy: MigrationElementModels.RichTextElement
	}
>
