/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { MigrationElementModels } from "@kontent-ai/migration-toolkit"
import type { CoreMigrationItem } from "../migration.generated"

/*
 * Landing Page
 *
 * Codename: landing_page
 * Id: 016a17a6-c9bb-4c03-866f-1205a00a769b
 */
export type LandingPageItem = CoreMigrationItem<
	"landing_page",
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: 07957699-6d50-4772-98f6-6d23c1f47c20
		 * Type: text
		 * Required: true
		 */
		readonly title: MigrationElementModels.TextElement

		/*
		 * Hero image
		 *
		 * Codename: hero_image
		 * Id: 82db1546-2ce1-40a5-8d47-05ba28522226
		 * Type: asset
		 * Required: true
		 */
		readonly hero_image: MigrationElementModels.AssetElement

		/*
		 * Body Copy
		 *
		 * Codename: body_copy
		 * Id: 61691ef9-cef2-4807-8d29-fa2c001d34f5
		 * Type: rich_text
		 * Required: false
		 */
		readonly body_copy: MigrationElementModels.RichTextElement

		/*
		 * Featured Products
		 *
		 * Codename: featured_products
		 * Id: b05063d4-beec-47c9-b3a6-6cfc9d65a012
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: product
		 */
		readonly featured_products: MigrationElementModels.LinkedItemsElement

		/*
		 * Call to Action
		 *
		 * Codename: call_to_action
		 * Id: c27e246e-b2b5-4557-a690-1e84fb17fa50
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: call_to_action
		 */
		readonly call_to_action: MigrationElementModels.LinkedItemsElement
	}
>
