/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { MigrationElementModels } from "@kontent-ai/migration-toolkit"
import type { CoreMigrationItem } from "../migration.generated"

/*
 * Page
 *
 * Codename: page
 * Id: bc28363e-f5a1-4cb3-805b-82f31ff3a784
 */
export type PageItem = CoreMigrationItem<
	"page",
	{
		/*
		 * Title
		 *
		 * Codename: title
		 * Id: c56f9d0e-2eca-40ee-89c5-a0844fa8daa6
		 * Type: text
		 * Required: true
		 */
		readonly title: MigrationElementModels.TextElement

		/*
		 * Body Copy
		 *
		 * Codename: body_copy
		 * Id: 3b980867-1078-4bc4-b462-ef9458514633
		 * Type: rich_text
		 * Required: false
		 */
		readonly body_copy: MigrationElementModels.RichTextElement

		/*
		 * Hero image
		 *
		 * Codename: hero_image
		 * Id: 87934b51-9a7d-4c8e-b3a9-f0ffb8397096
		 * Type: asset
		 * Required: true
		 */
		readonly hero_image: MigrationElementModels.AssetElement

		/*
		 * Product Type
		 *
		 * Codename: category
		 * Id: 8860d00d-042a-4843-ae78-e6555023c379
		 * Type: taxonomy
		 * Required: false
		 * Taxonomy: product_type
		 */
		readonly category: MigrationElementModels.TaxonomyElement
	}
>
