/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { MigrationElementModels } from "@kontent-ai/migration-toolkit"
import type { CoreMigrationItem } from "../migration.generated"

/*
 * Product
 *
 * Codename: product
 * Id: ea895149-eb50-409a-b3df-a57e59dbbc9b
 */
export type ProductItem = CoreMigrationItem<
	"product",
	{
		/*
		 * Name
		 *
		 * Codename: name
		 * Id: a13af2be-fa32-4d7e-aef2-d39e533aabe2
		 * Type: text
		 * Required: true
		 */
		readonly name: MigrationElementModels.TextElement

		/*
		 * Images
		 *
		 * Codename: images
		 * Id: 0aa8d455-ef70-46a6-b02b-c870903b3c66
		 * Type: asset
		 * Required: true
		 */
		readonly images: MigrationElementModels.AssetElement

		/*
		 * Product Type
		 *
		 * Codename: product_type
		 * Id: 17ba34bb-fba7-4d09-b9da-c3867e96ee9f
		 * Type: taxonomy
		 * Required: true
		 * Taxonomy: product_type
		 */
		readonly product_type: MigrationElementModels.TaxonomyElement

		/*
		 * Body Benefits
		 *
		 * Codename: body_benefits
		 * Id: 316c4d72-ef4e-4c45-b681-1c1ff958f42a
		 * Type: taxonomy
		 * Required: true
		 * Taxonomy: body_benefits
		 */
		readonly body_benefits: MigrationElementModels.TaxonomyElement

		/*
		 * More Information
		 *
		 * Codename: more_information
		 * Id: a4264c82-f21e-4eab-97e7-da354002ac1c
		 * Type: rich_text
		 * Required: false
		 */
		readonly more_information: MigrationElementModels.RichTextElement

		/*
		 * About the Product
		 *
		 * Codename: about_the_product
		 * Id: 9d6f8549-bc97-4aaf-9bdc-6861acbab967
		 * Type: rich_text
		 * Required: false
		 */
		readonly about_the_product: MigrationElementModels.RichTextElement

		/*
		 * How to use
		 *
		 * Codename: how_to_use
		 * Id: 75e5a725-76d9-4f5d-87a9-34bb78e6ed25
		 * Type: rich_text
		 * Required: false
		 */
		readonly how_to_use: MigrationElementModels.RichTextElement

		/*
		 * Our formula
		 *
		 * Codename: our_formula
		 * Id: b5c7829a-8696-480b-935b-f113df5dc8ac
		 * Type: rich_text
		 * Required: false
		 */
		readonly our_formula: MigrationElementModels.RichTextElement

		/*
		 * Quality Assurance
		 *
		 * Codename: quality_assurance
		 * Id: 69e17eb6-20f3-40ac-8a4a-551c0979e848
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: disclaimer
		 */
		readonly quality_assurance: MigrationElementModels.LinkedItemsElement

		/*
		 * Recommended Products
		 *
		 * Codename: recommended_products
		 * Id: 74e9df3e-0e1f-4bd5-ae05-fac678b51e16
		 * Type: modular_content
		 * Required: false
		 * Allowed content types: product
		 */
		readonly recommended_products: MigrationElementModels.LinkedItemsElement

		/*
		 * Product Catalog
		 *
		 * Codename: product_catalog
		 * Id: b1f8b5a3-71c3-4833-8bb9-34e478e2667b
		 * Type: custom
		 * Required: true
		 * Guidelines: CommerceTools integration via custom element
		 */
		readonly product_catalog: MigrationElementModels.CustomElement

		/*
		 * API Previewer
		 *
		 * Codename: api_previewer
		 * Id: a6191779-ce6a-479b-a5ad-2facb0355f5a
		 * Type: custom
		 * Required: false
		 */
		readonly api_previewer: MigrationElementModels.CustomElement
	}
>
