/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { MigrationElements, MigrationItem, MigrationItemSystem } from "@kontent-ai/migration-toolkit"
import type {
	CollectionCodenames,
	ContentTypeCodenames,
	LanguageCodenames,
	WorkflowCodenames,
	WorkflowStepCodenames
} from "./environment/environment.generated"

/*
 * System object shared by all individual content type models
 */
export type CoreMigrationItemSystem<TCodename extends ContentTypeCodenames> = MigrationItemSystem<
	TCodename,
	LanguageCodenames,
	CollectionCodenames,
	WorkflowCodenames
>

/*
 * Item object shared by all individual content type models
 */
export type CoreMigrationItem<
	TCodename extends ContentTypeCodenames,
	TElements extends MigrationElements = MigrationElements
> = MigrationItem<TElements, CoreMigrationItemSystem<TCodename>, WorkflowStepCodenames>
