/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

import type { LanguageCodenames } from "../system/languages.generated"

/*
 * Type representing codename of 'Default project language' language
 */
export type DefaultProjectLanguageLanguageCodename = keyof Pick<Record<LanguageCodenames, null>, "default">

/*
 * Typeguard for codename of 'Default project language' language
 */
export function isDefaultProjectLanguageLanguageCodename(
	value: string | undefined | null
): value is DefaultProjectLanguageLanguageCodename {
	return typeof value === "string" && value === ("default" satisfies DefaultProjectLanguageLanguageCodename)
}
