/*
 * This file has been auto-generated by '@kontent-ai/sync-sdk@9.1.0'.
 * 
 * (c) Kontent.ai
 *  
 * -------------------------------------------------------------------------------
 * 
 * Project: Usana Angular
 * Environment: Production
 * Id: 2d0653cd-a8dd-00ea-3fca-403eccd094c6
 * 
 * -------------------------------------------------------------------------------
 */

/*
 * Type representing all languages
 */
export type LanguageCodenames = "default"

/*
 * Type representing all content types
 */
export type ContentTypeCodenames = "call_to_action" | "disclaimer" | "landing_page" | "page" | "product"

/*
 * Type representing all collections
 */
export type CollectionCodenames = "default"

/*
 * Type representing all workflows
 */
export type WorkflowCodenames = "default"

/*
 * Type representing all worksflow steps across all workflows
 */
export type WorkflowStepCodenames = "archived" | "draft" | "published" | "scheduled"
